-- =============================================================================
-- Generated by scripts/apply-supabase.mjs — paste into Supabase SQL Editor.
-- Project: https://wkifwiiagbbjargrrsiw.supabase.co
-- Applies the normalized dunning schema (0001–0008) and drops the old flat
-- schema (0099). All statements are idempotent, so this is safe to re-run.
-- =============================================================================

-- ---- 0001_webhook_receipts.sql ----
-- =============================================================================
-- 0001 — webhook_receipts + shared helpers
-- A durable receipt for every Stripe webhook. stripe_event_id is the
-- idempotency key: Stripe redelivers events, so we must never process the
-- same event twice.
-- =============================================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Shared "updated_at" trigger, used by several tables later in the chain.
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TABLE IF NOT EXISTS public.webhook_receipts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  stripe_event_id text NOT NULL UNIQUE,
  event_type text NOT NULL,
  raw_payload jsonb NOT NULL,
  status text NOT NULL DEFAULT 'processed'
    CHECK (status IN ('processed', 'failed', 'ignored')),
  error text,
  received_at timestamptz NOT NULL DEFAULT now(),
  processed_at timestamptz
);

CREATE INDEX IF NOT EXISTS idx_webhook_receipts_event_type
  ON public.webhook_receipts (event_type);
CREATE INDEX IF NOT EXISTS idx_webhook_receipts_received_at
  ON public.webhook_receipts (received_at DESC);

ALTER TABLE public.webhook_receipts DISABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.webhook_receipts
  TO anon, authenticated, service_role;


-- ---- 0002_customers_subscriptions.sql ----
-- =============================================================================
-- 0002 — customers + subscriptions
-- customers:      one row per Stripe customer.
-- subscriptions:  one row per Stripe subscription — required to correctly
--                 support customers who hold more than one subscription.
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.customers (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  stripe_customer_id text NOT NULL UNIQUE,
  email text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.subscriptions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  customer_id uuid NOT NULL REFERENCES public.customers (id) ON DELETE CASCADE,
  stripe_subscription_id text NOT NULL UNIQUE,
  status text NOT NULL DEFAULT 'active'
    CHECK (status IN (
      'trialing', 'active', 'past_due', 'canceled',
      'incomplete', 'incomplete_expired', 'unpaid', 'paused'
    )),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_subscriptions_customer_id
  ON public.subscriptions (customer_id);
CREATE INDEX IF NOT EXISTS idx_subscriptions_status
  ON public.subscriptions (status);

DROP TRIGGER IF EXISTS trg_customers_updated_at ON public.customers;
CREATE TRIGGER trg_customers_updated_at
  BEFORE UPDATE ON public.customers
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS trg_subscriptions_updated_at ON public.subscriptions;
CREATE TRIGGER trg_subscriptions_updated_at
  BEFORE UPDATE ON public.subscriptions
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.customers DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.subscriptions DISABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.customers TO anon, authenticated, service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.subscriptions TO anon, authenticated, service_role;


-- ---- 0003_dunning_cycles_attempts.sql ----
-- =============================================================================
-- 0003 — dunning_cycles + dunning_attempts
-- A cycle = one invoice that entered dunning. A new billing period always
-- opens a new cycle, so a stale 'active' from a prior period never suppresses
-- the new period's emails.
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.dunning_cycles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  subscription_id uuid NOT NULL REFERENCES public.subscriptions (id) ON DELETE CASCADE,
  customer_id uuid NOT NULL REFERENCES public.customers (id) ON DELETE CASCADE,
  invoice_id text NOT NULL UNIQUE,
  status text NOT NULL DEFAULT 'active'
    CHECK (status IN ('active', 'recovered', 'exhausted')),
  resolution_type text
    CHECK (resolution_type IN (
      'original_invoice_paid', 'card_updated_new_invoice', 'canceled', 'exhausted'
    )),
  stripe_retry_count integer NOT NULL DEFAULT 0,
  amount_due integer NOT NULL DEFAULT 0,
  amount_remaining integer NOT NULL DEFAULT 0,
  started_at timestamptz NOT NULL DEFAULT now(),
  resolved_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_dunning_cycles_subscription
  ON public.dunning_cycles (subscription_id);
CREATE INDEX IF NOT EXISTS idx_dunning_cycles_status
  ON public.dunning_cycles (status);
CREATE INDEX IF NOT EXISTS idx_dunning_cycles_started_at
  ON public.dunning_cycles (started_at DESC);

CREATE TABLE IF NOT EXISTS public.dunning_attempts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  dunning_cycle_id uuid NOT NULL REFERENCES public.dunning_cycles (id) ON DELETE CASCADE,
  stripe_decline_code text NOT NULL,
  decline_category text NOT NULL
    CHECK (decline_category IN ('soft_retry', 'hard_update_required', 'auth_required', 'final_notice')),
  attempt_number integer NOT NULL DEFAULT 1,
  amount_due integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_dunning_attempts_cycle
  ON public.dunning_attempts (dunning_cycle_id);
CREATE INDEX IF NOT EXISTS idx_dunning_attempts_category
  ON public.dunning_attempts (decline_category);

DROP TRIGGER IF EXISTS trg_dunning_cycles_updated_at ON public.dunning_cycles;
CREATE TRIGGER trg_dunning_cycles_updated_at
  BEFORE UPDATE ON public.dunning_cycles
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.dunning_cycles DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.dunning_attempts DISABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.dunning_cycles TO anon, authenticated, service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.dunning_attempts TO anon, authenticated, service_role;


-- ---- 0004_klaviyo_sends.sql ----
-- =============================================================================
-- 0004 — klaviyo_sends
-- The send ledger + the idempotency guards against double-sending:
--   1. UNIQUE (dunning_attempt_id, klaviyo_event_name) — one send per attempt/event.
--   2. Partial unique on (dunning_cycle_id, klaviyo_event_name) for off-ramp
--      events (payment_recovered / subscription_canceled) which have no attempt.
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.klaviyo_sends (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  customer_id uuid NOT NULL REFERENCES public.customers (id) ON DELETE CASCADE,
  dunning_cycle_id uuid NOT NULL REFERENCES public.dunning_cycles (id) ON DELETE CASCADE,
  dunning_attempt_id uuid REFERENCES public.dunning_attempts (id) ON DELETE SET NULL,
  klaviyo_event_name text NOT NULL,
  status text NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'sent', 'failed')),
  response_payload jsonb,
  error text,
  retry_count integer NOT NULL DEFAULT 0,
  next_retry_at timestamptz NOT NULL DEFAULT now(),
  sent_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (dunning_attempt_id, klaviyo_event_name)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_klaviyo_sends_offramp_per_cycle
  ON public.klaviyo_sends (dunning_cycle_id, klaviyo_event_name)
  WHERE dunning_attempt_id IS NULL;

CREATE INDEX IF NOT EXISTS idx_klaviyo_sends_status
  ON public.klaviyo_sends (status);
CREATE INDEX IF NOT EXISTS idx_klaviyo_sends_created_at
  ON public.klaviyo_sends (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_klaviyo_sends_pending_retry
  ON public.klaviyo_sends (status, next_retry_at);

DROP TRIGGER IF EXISTS trg_klaviyo_sends_updated_at ON public.klaviyo_sends;
CREATE TRIGGER trg_klaviyo_sends_updated_at
  BEFORE UPDATE ON public.klaviyo_sends
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.klaviyo_sends DISABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.klaviyo_sends TO anon, authenticated, service_role;


-- ---- 0005_dead_letter_events.sql ----
-- =============================================================================
-- 0005 — dead_letter_events
-- If a Supabase write fails while handling a webhook, the raw event lands here
-- instead of being dropped, so it can be replayed later. The webhook still
-- returns 200 to Stripe (Stripe did its job; we replay from this table).
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.dead_letter_events (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  stripe_event_id text,
  event_type text NOT NULL,
  raw_payload jsonb NOT NULL,
  error text,
  replay_attempts integer NOT NULL DEFAULT 0,
  replayed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_dead_letter_replay_attempts
  ON public.dead_letter_events (replay_attempts);

ALTER TABLE public.dead_letter_events DISABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.dead_letter_events TO anon, authenticated, service_role;


-- ---- 0006_simulator_attempts.sql ----
-- =============================================================================
-- 0006 — simulator_attempts
-- Rate-limiting ledger for the Stripe failure simulator (per IP + email).
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.simulator_attempts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  ip_address text NOT NULL,
  email text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_simulator_attempts_ip
  ON public.simulator_attempts (ip_address, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_simulator_attempts_email
  ON public.simulator_attempts (email, created_at DESC);

ALTER TABLE public.simulator_attempts DISABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.simulator_attempts TO anon, authenticated, service_role;


-- ---- 0007_reporting_views.sql ----
-- =============================================================================
-- 0007 — reporting views (dashboard + alerting)
-- =============================================================================

-- Recovery rate + time-to-recovery by decline category.
CREATE OR REPLACE VIEW public.recovery_by_category AS
SELECT
  da.decline_category,
  count(*) AS attempts,
  count(*) FILTER (WHERE dc.status = 'recovered') AS recovered,
  round(
    100.0 * count(*) FILTER (WHERE dc.status = 'recovered') / nullif(count(*), 0),
    1
  ) AS recovery_rate_pct,
  round(
    avg(extract(epoch FROM (dc.resolved_at - dc.started_at)) / 3600)
      FILTER (WHERE dc.status = 'recovered'),
    1
  ) AS avg_time_to_recovery_hours
FROM public.dunning_attempts da
JOIN public.dunning_cycles dc ON dc.id = da.dunning_cycle_id
GROUP BY da.decline_category;

-- Active cycles + how long they've been running (for the "approaching
-- cancellation" threshold in the dashboard).
CREATE OR REPLACE VIEW public.active_dunning_cycles AS
SELECT
  dc.id,
  c.email,
  s.stripe_subscription_id,
  dc.invoice_id,
  dc.started_at,
  dc.amount_due,
  dc.amount_remaining,
  dc.stripe_retry_count,
  round(extract(epoch FROM (now() - dc.started_at)) / 3600, 1) AS hours_active
FROM public.dunning_cycles dc
JOIN public.customers c ON c.id = dc.customer_id
JOIN public.subscriptions s ON s.id = dc.subscription_id
WHERE dc.status = 'active';

-- Klaviyo send failures — must be alerted on, not just logged.
CREATE OR REPLACE VIEW public.klaviyo_send_failures AS
SELECT
  ks.id,
  c.email,
  ks.klaviyo_event_name,
  ks.error,
  ks.retry_count,
  ks.created_at
FROM public.klaviyo_sends ks
JOIN public.customers c ON c.id = ks.customer_id
WHERE ks.status = 'failed';

GRANT SELECT ON public.recovery_by_category TO anon, authenticated, service_role;
GRANT SELECT ON public.active_dunning_cycles TO anon, authenticated, service_role;
GRANT SELECT ON public.klaviyo_send_failures TO anon, authenticated, service_role;


-- ---- 0008_seed_demo.sql ----
-- =============================================================================
-- 0008 — deterministic demo seed (idempotent)
-- Populates the dashboard with realistic historical data so the portfolio
-- shows recovery analytics immediately. Uses fixed UUIDs so FKs are stable.
-- Safe to re-run: ON CONFLICT DO NOTHING.
-- =============================================================================

INSERT INTO public.customers (id, stripe_customer_id, email) VALUES
  ('c0000000-0000-4000-8000-000000000001', 'cus_demo_001', 'sarah.chen@example.com'),
  ('c0000000-0000-4000-8000-000000000002', 'cus_demo_002', 'marcus.reyes@example.com'),
  ('c0000000-0000-4000-8000-000000000003', 'cus_demo_003', 'priya.nair@example.com')
ON CONFLICT (stripe_customer_id) DO NOTHING;

INSERT INTO public.subscriptions (id, customer_id, stripe_subscription_id, status) VALUES
  ('11111111-0000-4000-8000-000000000001', 'c0000000-0000-4000-8000-000000000001', 'sub_demo_001', 'active'),
  ('11111111-0000-4000-8000-000000000002', 'c0000000-0000-4000-8000-000000000002', 'sub_demo_002', 'past_due'),
  ('11111111-0000-4000-8000-000000000003', 'c0000000-0000-4000-8000-000000000003', 'sub_demo_003', 'active')
ON CONFLICT (stripe_subscription_id) DO NOTHING;

-- Cycle A: recovered via original invoice paid (soft retry).
INSERT INTO public.dunning_cycles
  (id, subscription_id, customer_id, invoice_id, status, resolution_type,
   stripe_retry_count, amount_due, amount_remaining, started_at, resolved_at)
VALUES
  ('d0000000-0000-4000-8000-000000000001', '11111111-0000-4000-8000-000000000001',
   'c0000000-0000-4000-8000-000000000001', 'in_demo_001', 'recovered', 'original_invoice_paid',
   2, 4900, 0, now() - interval '5 days', now() - interval '3 days')
ON CONFLICT (invoice_id) DO NOTHING;

-- Cycle B: active, hard decline, still dunning.
INSERT INTO public.dunning_cycles
  (id, subscription_id, customer_id, invoice_id, status, resolution_type,
   stripe_retry_count, amount_due, amount_remaining, started_at)
VALUES
  ('d0000000-0000-4000-8000-000000000002', '11111111-0000-4000-8000-000000000002',
   'c0000000-0000-4000-8000-000000000002', 'in_demo_002', 'active', NULL,
   0, 4900, 4900, now() - interval '6 hours')
ON CONFLICT (invoice_id) DO NOTHING;

-- Cycle C: exhausted (gave up / canceled).
INSERT INTO public.dunning_cycles
  (id, subscription_id, customer_id, invoice_id, status, resolution_type,
   stripe_retry_count, amount_due, amount_remaining, started_at, resolved_at)
VALUES
  ('d0000000-0000-4000-8000-000000000003', '11111111-0000-4000-8000-000000000003',
   'c0000000-0000-4000-8000-000000000003', 'in_demo_003', 'exhausted', 'exhausted',
   4, 4900, 4900, now() - interval '14 days', now() - interval '7 days')
ON CONFLICT (invoice_id) DO NOTHING;

INSERT INTO public.dunning_attempts
  (id, dunning_cycle_id, stripe_decline_code, decline_category, attempt_number, amount_due, created_at)
VALUES
  ('a0000000-0000-4000-8000-000000000001', 'd0000000-0000-4000-8000-000000000001', 'insufficient_funds', 'soft_retry', 1, 4900, now() - interval '5 days'),
  ('a0000000-0000-4000-8000-000000000002', 'd0000000-0000-4000-8000-000000000001', 'insufficient_funds', 'soft_retry', 2, 4900, now() - interval '4 days'),
  ('a0000000-0000-4000-8000-000000000003', 'd0000000-0000-4000-8000-000000000002', 'expired_card', 'hard_update_required', 1, 4900, now() - interval '6 hours'),
  ('a0000000-0000-4000-8000-000000000004', 'd0000000-0000-4000-8000-000000000003', 'card_not_supported', 'hard_update_required', 1, 4900, now() - interval '14 days')
ON CONFLICT DO NOTHING;

INSERT INTO public.klaviyo_sends
  (id, customer_id, dunning_cycle_id, dunning_attempt_id, klaviyo_event_name, status, sent_at)
VALUES
  ('e0000000-0000-4000-8000-000000000001', 'c0000000-0000-4000-8000-000000000001', 'd0000000-0000-4000-8000-000000000001', 'a0000000-0000-4000-8000-000000000001', 'dunning-soft-retry', 'sent', now() - interval '5 days'),
  ('e0000000-0000-4000-8000-000000000002', 'c0000000-0000-4000-8000-000000000001', 'd0000000-0000-4000-8000-000000000001', 'a0000000-0000-4000-8000-000000000002', 'dunning-soft-retry', 'sent', now() - interval '4 days'),
  ('e0000000-0000-4000-8000-000000000003', 'c0000000-0000-4000-8000-000000000001', 'd0000000-0000-4000-8000-000000000001', NULL, 'payment_recovered', 'sent', now() - interval '3 days'),
  ('e0000000-0000-4000-8000-000000000004', 'c0000000-0000-4000-8000-000000000002', 'd0000000-0000-4000-8000-000000000002', 'a0000000-0000-4000-8000-000000000003', 'dunning-hard-update-required', 'sent', now() - interval '6 hours'),
  ('e0000000-0000-4000-8000-000000000005', 'c0000000-0000-4000-8000-000000000003', 'd0000000-0000-4000-8000-000000000003', 'a0000000-0000-4000-8000-000000000004', 'dunning-hard-update-required', 'sent', now() - interval '14 days')
ON CONFLICT DO NOTHING;


-- ---- 0099_legacy_cleanup.sql ----
-- =============================================================================
-- 0099 — legacy cleanup (drop the OLD flat schema)
-- The old flat schema (payment_failures, profiles, demo_requests + their views)
-- is replaced by the normalized dunning model in 0001–0008. Run this after
-- 0001–0008 so the portfolio shows one clean architecture and no dead tables.
--
-- Idempotent: DROP IF EXISTS + CASCADE.
-- =============================================================================

DROP VIEW IF EXISTS public.demo_conversion_funnel CASCADE;
DROP VIEW IF EXISTS public.dunning_resolution_by_industry CASCADE;
DROP VIEW IF EXISTS public.flow_performance CASCADE;
DROP VIEW IF EXISTS public.active_dunning_cases CASCADE;
DROP VIEW IF EXISTS public.customer_dunning_summary CASCADE;

DROP TABLE IF EXISTS public.payment_failures CASCADE;
DROP TABLE IF EXISTS public.profiles CASCADE;
DROP TABLE IF EXISTS public.demo_requests CASCADE;

-- Old trigger helper from the flat schema (dropped with the table's trigger,
-- but clean it up explicitly too).
DROP FUNCTION IF EXISTS public.update_payment_failures_updated_at() CASCADE;

